### ISSUE TITLE
Build instructions for Mac OS

### ISSUE THREAD

**Issue by halpz** [GTAmodding/re3#1063]
could you includ build instructions for mac OS on the wiki please? im trying to create an Apple Silicon executable from source, but not sure which make file to run

**Comment by ShFil119** [comment]
Can you try to follow conan's steps for linux?

Basically you need to have python, conan(installed via pip) and compiler.

**Comment by halpz** [comment]
yeah I've tried, but I don't think Conan likes the 'arm64' architecture, I'll wait until someone else manages to do it!

**Comment by paer76** [comment]
Try the same as the premake linux . I recommend using Brew rather than macports to get your libs. oh and alway try building debugs version i never had any luck building the release or vanilla versions.

**Comment by paer76** [comment]
one last thing on premake avoid using xcode try gmake2 first

**Comment by Wintermute21** [comment]
the linux instructions do work on macOS 11.2 btw

**Comment by halpz** [comment]
has anyone got it to run on M1 mac without rosetta ?

**Comment by halpz** [comment]
im getting: `==== Building librw (release_macosx-arm64-librw_gl3_glfw-oal) ====
charset.cpp
In file included from ../vendor/librw/src/charset.cpp:14:
../vendor/librw/src/gl/rwgl3.h:2:10: fatal error: 'GL/glew.h' file not found
#include <GL/glew.h>`

even though i installed glew via homewbrew

**Comment by aap** [comment]
if you build librw separately (not as part ofr re3) it should work, we just got rid of the glew dependency there. will probably update re3 later today as well.

**Comment by ShFil119** [comment]
@aap I think it's not the issue, as git submodule points at commit and repo re3 wasn't updated yet.

**Comment by halpz** [comment]
I don't think that works either, or I'm doing something wrong

**Comment by halpz** [comment]
when building librw i get this:

```
==== Building librw (release) ====
charset.cpp
../src/charset.cpp:35:8: error: use of undeclared identifier 'RWDEVICE'
static RWDEVICE::Im2DVertex *vertices;
       ^
../src/charset.cpp:47:20: error: use of undeclared identifier 'RWDEVICE'
        vertices = rwNewT(RWDEVICE::Im2DVertex, NUMCHARS*4, MEMDUR_EVENT);
                          ^
../src/charset.cpp:47:13: error: expected expression
        vertices = rwNewT(RWDEVICE::Im2DVertex, NUMCHARS*4, MEMDUR_EVENT);
                   ^
../src/rwengine.h:217:28: note: expanded from macro 'rwNewT'
#define rwNewT(t, s, h) (t*)rw::mustmalloc_LOC((s)*sizeof(t),h,RWHERE)
                           ^
../src/charset.cpp:145:2: error: use of undeclared identifier 'RWDEVICE'
        RWDEVICE::Im2DVertex *vert;
        ^
4 errors generated.
make[1]: *** [obj/Release/librw/charset.o] Error 1
make: *** [librw] Error 2

```

**Comment by aap** [comment]
Hm, i have no explicit config for macos, maybe that's the problem. i'll see that re3 gets the glew stuff removed today, you'll just have to wait.

**Comment by Wintermute21** [comment]
@aap I had gotten similar errors trying to build using Xcode but not using premake so it could be an Xcode thing?

**Comment by halpz** [comment]
i downloaded premake binary from here:
https://premake.github.io/

**Comment by aap** [comment]
I updated librw and got rid of glew in premake now. so maybe try again.

**Comment by blattersturm** [comment]
> build using Xcode but not using premake

Uh, CMake, then, or did you manually place files?

**Comment by halpz** [comment]
thanks for the update, but now I'm getting:

`../vendor/librw/src/gl/rwgl3.h:6:10: fatal error: 'GLFW/glfw3.h' file not found
#include <GLFW/glfw3.h>`

**Comment by Wintermute21** [comment]
@blattersturm I had originally used Cmake to generate Xcode project files but had gotten the error above about namespaces but then I followed the linux instructions and those worked.

**Comment by halpz** [comment]
i managed to build it in the end, but was a bit of a hassle - i had to change a lot of the #include statements to recursively go back to see certain libraries. 

i believe M1 mac have their Homebrew packages installed in a different place (/opt/homebrew), that is not read by the code, which thinks they are in the normal PATH (/usr/local/bin)

**Comment by halpz** [comment]
there is probably a simple solution., but i'm not too familiar with c++ or shell scripts etc !

**Comment by halpz** [comment]
it wont run anyway looks like a wider issue:

```
Grand Theft Auto Vice City % ./reVC
cdvd_stream: can't get filesystem info
[DBG]: size of matrix 80
[DBG]: size of placeable 80
[DBG]: size of entity 120
[DBG]: size of building 120
[DBG]: size of dummy 128
[DBG-2]: [/Users/runner/work/re3/re3/src/skel/glfw/glfw.cpp.psInitialize:396]: gGameState = GS_START_UP
casepath couldn't find dir/file "gta_vc.set", full path was gta_vc.set
[DBG-2]: Default skin set as no other skins are available OR saved skin not found!
[DBG]: Physical memory size 1334038528
[DBG]: Available physical memory 17179869184
GLFW Error: NSGL: The targeted version of macOS only supports forward-compatible core profile contexts for OpenGL 3.2 and above
OpenGL version: 2.1 Metal - 71.0.7
casepath couldn't find dir/file "coll", full path was models\coll\peds.col
zsh: segmentation fault  ./reVC
```

**Comment by Laci-Strucc** [comment]
can confirm above, having the same output bang on on MacOS Big Sur (OpenCore with Intel)

**Comment by halpz** [comment]
@Laci-Strucc ah this is when you select 'replace' instead of 'merge' when copying the game data files
the pre-built x86-64 mac binary works in rosetta this way

**Comment by halpz** [comment]
when launching arm build, you see the splash screen for a split second then crashes:
```

% ./re3
[DBG]: cdvd_stream: read info 0x12d708b90
[DBG]: Using one streaming thread for all channels
[DBG]: Created cdstream thread
[DBG-2]: [../src/skel/glfw/glfw.cpp.psInitialize:397]: gGameState = GS_START_UP
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: Default skin set as no other skins are available OR saved skin not found!
[DBG]: Physical memory size 548962304
[DBG]: Available physical memory 17179869184
GLFW Error: NSGL: The targeted version of macOS only supports forward-compatible core profile contexts for OpenGL 3.2 and above
OpenGL version: 2.1 Metal - 71.0.7
casepath couldn't find dir/file "gta3.set", full path was gta3.set
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1732]: gGameState = GS_INIT_ONCE
[DBG]: Loadind audio cache (If game crashes around here, then your cache is corrupted, remove audio/sound.cache)
[DBG-2]: Finding MP3s...
[DBG-2]: /Users/paul/Documents/Grand Theft Auto 3\MP3\
[DBG]: Initialising CTimer...
[DBG-2]: Performance counter not available, using millesecond timer

[DBG]: CTimer ready
[DBG]: Initialising CPedStats...
[DBG]: Loading pedstats data...
[DBG]: CPedStats ready
[DBG]: Intialising CTimeCycle...
[DBG]: CTimeCycle ready
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1824]: gGameState = GS_INIT_FRONTEND;
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1846]: gGameState = GS_FRONTEND;
LOAD frontend
LOAD sprite
zsh: segmentation fault  ./re3
% 

```

**Comment by Laci-Strucc** [comment]
nope, same stuff unfortunately. Still segfaults like crazy

**Comment by halpz** [comment]
latest commit (19th feb) is working for me now!
steps I had to take for M1 mac:

```
• install the required libraries with homebrew
• build premake5 from source (mac os gmake2)
• clone re3 repo, copy premake5 to re3 folder
• cd re3
• ./premake5 --with-librw gmake2
• go into build folder and edit the 2 files 'librw.make' and 're3.make'
• replace all instances of '/usr/local' with /opt/homebrew' and remove '-std=gnu++14' from 'ALL_CFLAGS' (for your desired config at least)
• then make config=release_macosx-arm64-librw_gl3_glfw-oal
```

**Comment by halpz** [comment]
Vice city branch doesn't run though, followed the same steps, but getting this:

```
 % ./reVC
[DBG]: cdvd_stream: read info 0x12e207320
[DBG]: Using one streaming thread for all channels
[DBG]: Created cdstream thread
[DBG]: size of matrix 80
[DBG]: size of placeable 80
[DBG]: size of entity 120
[DBG]: size of building 120
[DBG]: size of dummy 128
casepath couldn't find dir/file "TEXT", full path was \\TEXT\
zsh: segmentation fault  ./reVC
```

**Comment by erorcun** [comment]
exact same problem was reported to me via reddit, you can see the 2 possible solutions from here: https://github.com/GTAmodding/re3/issues/1085

**Comment by halpz** [comment]
that worked, I used `sudo chmod a+x reVC`

**Comment by erorcun** [comment]
glad to hear that.
i'm planning to keep both '/usr/local' and '/opt/homebrew' paths, can you try compiling it when both paths is there in premake5.lua?
i.e., these lines:
```
includedirs { "/usr/local/opt/openal-soft/include" }
libdirs { "/usr/local/opt/openal-soft/lib" }
```
should be like that:
```
includedirs { "/usr/local/opt/openal-soft/include" }
libdirs { "/usr/local/opt/openal-soft/lib" }
includedirs { "/opt/homebrew/opt/openal-soft/include" }
libdirs { "/opt/homebrew/opt/openal-soft/lib" }
```

**Comment by halpz** [comment]
i tried this and get this error:

`invalid argument '-std=gnu++14' not allowed with 'C'`

it can be fixed by removing -std=gnu++14 from ALL_CFLAGS, but not CPPFLAGS

**Comment by halpz** [comment]
(which i can only see in the generated .make files, not sure where to put that in the lua script

**Comment by halpz** [comment]
like this:

```
else ifeq ($(config),release_macosx-arm64-librw_gl3_glfw-oal)
TARGETDIR = ../bin/macosx-arm64-librw_gl3_glfw-oal/Release
TARGET = $(TARGETDIR)/re3.app
OBJDIR = obj/macosx-arm64-librw_gl3_glfw-oal/Release/re3
DEFINES += -DNDEBUG -DRW_GL3 -DAUDIO_OAL -DLIBRW
INCLUDES += -I../src -I../src/animation -I../src/audio -I../src/audio/eax -I../src/audio/oal -I../src/buildings -I../src/collision -I../src/control -I../src/core -I../src/entities -I../src/math -I../src/modelinfo -I../src/objects -I../src/peds -I../src/render -I../src/rw -I../src/save -I../src/skel -I../src/skel/glfw -I../src/text -I../src/vehicles -I../src/weapons -I../src/extras -I/usr/local/opt/openal-soft/include -I/opt/homebrew/opt/openal-soft/include -I../src/fakerw -I../vendor/librw -I/opt/local/include -I/usr/local/include -I/opt/homebrew/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -g -target arm64-apple-macos11
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O3 -g -target arm64-apple-macos11 -std=gnu++14
ALL_LDFLAGS += $(LDFLAGS) -L/usr/local/opt/openal-soft/lib -L/opy/homebrew/opt/openal-soft/lib -L../vendor/librw/lib/macosx-arm64-librw_gl3_glfw-oal/Release -L/opt/local/lib -L/usr/local/lib -L/opt/homebrew/lib -framework OpenGL

```

**Comment by erorcun** [comment]
i mean you should add those *on top of* your working premake5.lua. i know it won't build otherwise

**Comment by erorcun** [comment]
i think you didn't understand, so i'm closing the issue and will push it without testing. you can write here if mac build brokes again
